name: Update Docker Hub Description

on:
  push:
    branches: [ 'main' ]
    paths: [ 'README.md' ]
  workflow_dispatch:

env:
  DOCKERHUB_IMAGE: genericmale/protonvpn

jobs:
  dockerHubDescription:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@e98e4d1628a5f3be2be7c231e50981aee98723ae # v4.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          short-description: ${{ github.event.repository.description }}
          repository: ${{ env.DOCKERHUB_IMAGE }}
