name: Update Docker Hub Description

on:
  push:
    branches: [ 'main' ]
    paths: [ 'README.md' ]
  workflow_dispatch:

env:
  DOCKERHUB_IMAGE: genericmale/protonvpn

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          short-description: ${{ github.event.repository.description }}
          repository: ${{ env.DOCKERHUB_IMAGE }}
