name: Lint & Test

on: [ push, pull_request, workflow_dispatch ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install kcov & bashunit
        run: |
          sudo apt-get update
          sudo apt-get install kcov
          curl -s https://bashunit.typeddevs.com/install.sh
      - name: Execute Tests
        run: |
          kcov --include-path=src /tmp ./bashunit ./test --log-junit /tmp/TEST-bashunit.xml
          cp $(find /tmp -name 'cobertura.xml') /tmp/coverage.xml
      - name: Upload ShellCheck Report
        uses: actions/upload-artifact@v4
        with:
          name: bashunit-report
          path: |
            /tmp/TEST-bashunit.xml
            /tmp/coverage.xml

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install shellcheck
      - name: Run ShellCheck
        run: shellcheck --format=checkstyle $(find . -type f -name "*.sh") > /tmp/analysis.xml
      - name: Upload ShellCheck Report
        uses: actions/upload-artifact@v4
        with:
          name: shellcheck-report
          path: /tmp/analysis.xml

  upload:
    runs-on: ubuntu-latest
    needs: [ test, lint ]
    if: always()
    steps:
      - uses: actions/checkout@v4
      - name: Download Reports
        uses: actions/download-artifact@v4
        with:
          path: test/reports
          merge-multiple: true
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}
      - name: Push results to Testspace
        run: testspace test/reports/*.xml{test}
