name: Test

on:
  push:
    paths: [ 'src/**', 'spec/**' ]
  pull_request:
    paths: [ 'src/**', 'spec/**' ]
  workflow_dispatch:

env:
  TEST_BADGE_GIST_ID: d11c7cec7a928d0f605db3682ad2678c
  TEST_BADGE_GIST_FILE: test-badge.json

jobs:
  busybox:
    runs-on: ubuntu-24.04
    permissions:
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Download JQ
        run: |
          wget https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-linux-amd64 -O jq
          chmod +x jq
      - name: Run tests on busybox
        uses: docker://shellspec/shellspec@sha256:39346b73db30d00001355a3e6e3138396a20d2d90245a37c619520630b8a9b3e # 0.28.1-kcov
        continue-on-error: true
        with:
          args: -s "busybox ash" -o junit
        env:
          PATH: /github/workspace:/opt/shellspec:/usr/local/bin:/usr/bin:/bin
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@82082dac68ad6a19d980f8ce817e108b9f496c2a # v2.17.1
        id: test-results
        with:
          files: report/results_junit.xml
      - name: Generate Test Badge Data
        id: test-badge
        run: |
          tests=${{fromJSON(steps.test-results.outputs.json).stats.tests}}
          succ=${{fromJSON(steps.test-results.outputs.json).stats.tests_succ}}
          fail=$((${{fromJSON(steps.test-results.outputs.json).stats.tests_fail}} + ${{fromJSON(steps.test-results.outputs.json).stats.tests_error}}))
          skip=${{fromJSON(steps.test-results.outputs.json).stats.tests_skip}}
          
          message="$([[ $succ -eq 0 ]] || echo "✔ $succ | ")$([[ $fail -eq 0 ]] || echo "✘ $fail | ")$([[ $skip -eq 0 ]] || echo "➟ $skip | ")"
          echo "message=$([[ $tests -eq 0 ]] && echo "no tests" || echo "${message::-3}")" >> $GITHUB_OUTPUT
          
          color="$(([[ $fail -gt 0 ]] && echo "red") || ([[ $succ -eq 0 ]] && echo "yellow") || ([[ $skip -gt 0 ]] && echo "green") || echo "brightgreen")"
          echo "color=$color" >> $GITHUB_OUTPUT
      - name: Update Test Badge Gist
        uses: schneegans/dynamic-badges-action@e9a478b16159b4d31420099ba146cdc50f134483 # v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ env.TEST_BADGE_GIST_ID }}
          filename: ${{ env.TEST_BADGE_GIST_FILE }}
          label: tests
          message: ${{ steps.test-badge.outputs.message }}
          color: ${{ steps.test-badge.outputs.color }}
  bash:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Download JQ
        run: |
          wget https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-linux-amd64 -O jq
          chmod +x jq
      - name: Run tests with coverage
        uses: docker://shellspec/shellspec@sha256:39346b73db30d00001355a3e6e3138396a20d2d90245a37c619520630b8a9b3e # 0.28.1-kcov
        continue-on-error: true
        with:
          args: -s "bash" --kcov
        env:
          PATH: /github/workspace:/opt/shellspec:/usr/local/bin:/usr/bin:/bin
      - name: Publish Coverage
        uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699 # v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/cobertura.xml
