name: Test

on: [ push, pull_request, workflow_dispatch ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Install kcov & shellspec
        run: |
          sudo apt-get update
          sudo apt-get install kcov busybox
          curl -fsSL https://git.io/shellspec | sh -s 0.28.1 --yes
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - name: Run tests with coverage
        run: shellspec -s "bash" --kcov
      - name: Run tests on busybox
        run: shellspec -s "busybox ash" -o junit
      - name: Publish Coverage
        uses: codacy/codacy-coverage-reporter-action@v1
        if: always()
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/cobertura.xml
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: report/results_junit.xml
